---
abstract: 'test statistics about your DBIx::Class calls'
author:
  - 'osfameron <osfameron@cpan.org> 2014'
  - osfameron
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::DBIx::Class: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.08'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-DBIx-Class-Stats
no_index:
  directory:
    - inc
    - t
requires:
  DBIx::Class: 0
  Moo: 0
  MooX::HandlesVia: 0
  Test::More: 0.42
  Time::HiRes: 0
resources:
  license: http://dev.perl.org/licenses/
version: '0.01'
